version: "3.4"

services:

  jikan-rest:
    build:
      context: jikan
      dockerfile: Dockerfile
    depends_on:
      - jikan-redis
    ports:
      - "9001:80"
    networks:
      - default
    restart: always
    container_name: jikan-rest-api

  jikan-redis:
    image: redis:5.0.6-buster
    restart: always
    container_name: jikan-rest-redis
